In [6]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sms

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

from sklearn.preprocessing import scale
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import mean_squared_error, r2_score

In [10]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [11]:
from warnings import filterwarnings
filterwarnings("ignore")

Dataset provided from WHO, UN, World Bank

In [15]:
import os
# relative to `pwd`/data
datafile = os.path.join(os.getcwd(), "data", "life_expectancy_who_un.csv")
if not os.path.exists(datafile):
    print("Error")

Read the data into a Pandas dataframe, drop NaNs, make deep copies for stats processing and filtering

In [17]:
life_data = life_expectancy_data = pd.read_csv(datafile)

In [19]:
data = life_data.copy()
# drop NaN or fillna() with data.mean() inplace
data.dropna(inplace = True)

In [41]:
lindata = data.copy()
multidata = data.copy()
polydata = data.copy()
rf_data = data.copy()
logdata = data.copy()

Fit a line through scatter data via [Linear Regression](http://www.stat.yale.edu/Courses/1997-98/101/linreg.htm)

In [42]:
lindata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1649 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          1649 non-null   object
 1   Year                             1649 non-null   int64
 2   Status                           1649 non-null   object
 3   Life expectancy                  1649 non-null   float64
 4   Adult Mortality                  1649 non-null   float64
 5   infant deaths                    1649 non-null   int64
 6   Alcohol                          1649 non-null   float64
 7   percentage expenditure           1649 non-null   float64
 8   Hepatitis B                      1649 non-null   float64
 9   Measles                          1649 non-null   int64
 10   BMI                             1649 non-null   float64
 11  under-five deaths                1649 non-null   int64
 12  Polio                            1649 non-null   float64
 13  Total expenditure                1649 non-null   float64
 14  Diphtheria                       1649 non-null   float64
 15   HIV/AIDS                        1649 non-null   float64
 16  GDP                              1649 non-null   float64
 17  Population                       1649 non-null   float64
 18   thinness  1-19 years            1649 non-null   float64
 19   thinness 5-9 years              1649 non-null   float64
 20  Income composition of resources  1649 non-null   float64
 21  Schooling                        1649 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 360.8+ KB

In [43]:
lindata.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [44]:
lindata["Country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
2933       Zimbabwe
2934       Zimbabwe
2935       Zimbabwe
2936       Zimbabwe
2937       Zimbabwe
Name: Country, Length: 1649, dtype: object

In [141]:
#pt_data = test[test["Country"] == "Sweden"]
#pt_data.head()

#for i in list(lindata):
    # show the list of values  
#    print(lindata[i].tolist())

In [136]:
df = lindata.copy()

In [139]:
df[df["Country"].str.match("Portugal")]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2056,Portugal,2014,Developed,89.0,78.0,0,9.88,271.254553,98.0,0,...,98.0,9.50,98.0,0.1,2277.53613,14162.0,0.7,0.5,0.837,16.8
2057,Portugal,2013,Developed,86.0,79.0,0,10.00,2698.018170,98.0,1,...,98.0,9.55,98.0,0.1,21618.73534,1457295.0,0.7,0.5,0.827,16.3
2058,Portugal,2012,Developed,83.0,81.0,0,11.96,331.457035,98.0,23,...,98.0,9.74,98.0,0.1,2577.42640,1514844.0,0.7,0.5,0.824,16.3
2059,Portugal,2011,Developed,82.0,85.0,0,11.92,3108.288623,97.0,2,...,97.0,1.70,97.0,0.1,23196.18375,155756.0,0.7,0.5,0.818,16.2
2060,Portugal,2010,Developed,79.6,88.0,0,12.25,3119.349824,97.0,5,...,97.0,1.44,98.0,0.1,22538.65480,15731.0,0.7,0.5,0.812,16.0
2061,Portugal,2009,Developed,79.3,9.0,0,12.03,337.102352,96.0,3,...,96.0,1.42,96.0,0.1,2363.97161,1568247.0,0.7,0.5,0.809,16.0
2062,Portugal,2008,Developed,79.0,92.0,0,12.35,3652.869332,97.0,1,...,97.0,9.90,97.0,0.1,24815.68840,1558177.0,0.7,0.5,0.804,15.8
2063,Portugal,2007,Developed,78.7,94.0,0,12.57,333.356912,97.0,0,...,96.0,9.62,97.0,0.1,2278.58450,1542964.0,0.7,0.5,0.797,15.4
2064,Portugal,2006,Developed,78.5,96.0,0,13.11,2884.020194,97.0,0,...,97.0,9.67,97.0,0.1,19821.44463,1522288.0,0.7,0.5,0.793,15.4
2065,Portugal,2005,Developed,77.7,11.0,0,13.33,2813.985285,94.0,7,...,93.0,9.98,93.0,0.1,18784.94850,15333.0,0.7,0.6,0.790,15.4
2066,Portugal,2004,Developed,78.0,99.0,0,13.45,276.099980,94.0,5,...,95.0,9.84,95.0,0.1,1845.58810,1483861.0,0.7,0.6,0.792,15.9
2067,Portugal,2003,Developed,77.3,15.0,0,14.21,2283.891796,94.0,8,...,96.0,9.54,99.0,0.1,15772.73340,1458821.0,0.7,0.6,0.789,15.8
2068,Portugal,2002,Developed,77.2,17.0,1,12.00,1904.002310,82.0,8,...,96.0,9.15,98.0,0.1,12882.28897,1419631.0,0.8,0.6,0.788,15.9
2069,Portugal,2001,Developed,76.9,11.0,1,12.22,1657.328352,7.0,0,...,96.0,9.10,97.0,0.1,11729.14616,1362722.0,0.8,0.6,0.782,15.7
2070,Portugal,2000,Developed,76.6,11.0,1,11.89,167.328017,58.0,45,...,96.0,9.14,96.0,0.1,1152.39681,1289898.0,0.8,0.6,0.777,15.5